name: Build site on schedule or main branch update

on:
  push:
    branches:
      - main
  schedule:
    # Adjust refresh schedule here. By default, it runs once per hour.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm i
      - name: Build the feed
        run: npm run build
      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          COMMIT_NAME: "GitHub Action"
          COMMIT_EMAIL: "non-exist@example.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

